### ISSUE TITLE
CONTRIBUTING.md lacks information on default/expected workflow for contributing

### ISSUE THREAD

**Issue by daerogami** [Eerovil/thyme-toggl-cli#34]
I cloned the project to poke around. I am a C#/.NET developer so the typical python toolset/workflow is not fully familiar to me. Would it be possible to have `CONTRIBUTING.md` filled out with a "Getting Started" section on what steps are need to get a development instance running such as installing python, supported database engines, and running the app in development?

Thanks!

**Comment by eerovil** [comment]
There are no database requirements, as TrackLater uses a simple sqlite database through a pip package.

I'll update CONTRIBUTING.md with a basic development setup.
