### ISSUE TITLE
Tracking active window history

### ISSUE THREAD

**Issue by daerogami** [Eerovil/thyme-toggl-cli#35]
A helpful feature for this would be logging the active window. Sometimes, the time I have lost spans multiple tasks and knowing when the active window was for a specific project would help determine the division of time spent. Ideally this would be a hook, but polling every 1-5 minutes would be similarly useful.

[Related SO article](https://stackoverflow.com/questions/10266281/obtain-active-window-using-python)

If the `ctypes` approach is fast enough, this could be run on every mouse-click or tab as those are the common key presses for swapping windows. If the active window changes, the name is logged.

**Comment by eerovil** [comment]
Hey!

First of all, thanks for contributing the first feature request for TrackLater!

Back on-topic: Have you tried the thyme module? It's designed to show active windows as well: in the timeline view, hovering above a thyme-entry shows a list of top 10 windows active during it.

If there are problems setting it up on Windows I'd be happy to help.

**Comment by daerogami** [comment]
I hadn't ran the app yet. This is the first I've heard of Thyme. That's awesome!
